[2025-09-15 07:28:59]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 07:29:02] WARNING django.request - Not Found: /favicon.ico
[2025-09-15 07:29:05]   ERROR django.request - Internal Server Error: /purchase/injection/receipts/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\injection.py", line 146, in receipt_list
    .filter(status__in=["입고대기", "입고완료"])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1481, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1499, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1506, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1523, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1330, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'status' into field. Choices are: cancel_at, cancel_by, cancel_by_id, cancel_reason, created_at, created_by, created_by_id, dlt_yn, due_date, flow_status, id, incoming_inspections, io_receipt, items, order_date, order_lot, order_status, partner_shipments, receipts, shipping_registered_at, updated_at, updated_by, updated_by_id, use_yn, vendor, vendor_id
[2025-09-15 08:31:53]   ERROR django.request - Internal Server Error: /purchase/injection/receipts/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\injection.py", line 146, in receipt_list
    .filter(status__in=["입고대기", "입고완료"])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1481, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1499, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1506, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1523, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1330, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'status' into field. Choices are: cancel_at, cancel_by, cancel_by_id, cancel_reason, created_at, created_by, created_by_id, dlt_yn, due_date, flow_status, id, incoming_inspections, io_receipt, items, order_date, order_lot, order_status, partner_shipments, receipts, shipping_registered_at, updated_at, updated_by, updated_by_id, use_yn, vendor, vendor_id
[2025-09-15 08:52:09]   ERROR django.request - Internal Server Error: /purchase/injection/receipts/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\injection.py", line 146, in receipt_list
    .filter(status__in=["입고대기", "입고완료"])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1481, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1499, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1506, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1523, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1330, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'status' into field. Choices are: cancel_at, cancel_by, cancel_by_id, cancel_reason, created_at, created_by, created_by_id, dlt_yn, due_date, flow_status, id, incoming_inspections, io_receipt, items, order_date, order_lot, order_status, partner_shipments, receipts, shipping_registered_at, updated_at, updated_by, updated_by_id, use_yn, vendor, vendor_id
[2025-09-15 09:11:15] WARNING django.request - Not Found: /favicon.ico
[2025-09-15 10:25:00] WARNING django.request - Not Found: /favicon.ico
[2025-09-15 10:25:10] WARNING django.request - Not Found: /favicon.ico
[2025-09-15 10:25:11] WARNING django.request - Not Found: /sitemap.xml
[2025-09-15 11:05:22]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 11:05:23]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 11:05:57]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 11:05:57]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 11:07:03]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 11:07:03]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 11:07:28]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 11:07:28]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 11:08:59]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 11:08:59]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 11:09:44]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 11:09:44]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 11:43:39]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\vendor\models.py changed, reloading.
[2025-09-15 11:43:39]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 11:43:55]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\vendor\models.py changed, reloading.
[2025-09-15 11:43:56]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 11:44:10]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\vendor\models.py changed, reloading.
[2025-09-15 11:44:11]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 11:45:14]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\vendor\models.py changed, reloading.
[2025-09-15 11:45:15]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 11:45:27]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\vendor\models.py changed, reloading.
[2025-09-15 11:45:27]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 11:45:57]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\vendor\models.py changed, reloading.
[2025-09-15 11:45:58]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 11:46:33]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\vendor\forms.py changed, reloading.
[2025-09-15 11:46:34]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 11:46:41]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\vendor\forms.py changed, reloading.
[2025-09-15 11:46:42]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 11:46:56]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\vendor\forms.py changed, reloading.
[2025-09-15 11:46:57]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 11:47:23]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\vendor\forms.py changed, reloading.
[2025-09-15 11:47:23]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 11:53:58]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\vendor\forms.py changed, reloading.
[2025-09-15 11:53:58]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 11:57:58] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 12:07:16] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 12:08:14] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 12:08:17] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 12:08:41] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 12:45:32] WARNING django.request - Not Found: /favicon.ico
[2025-09-15 12:45:32] WARNING django.request - Not Found: /robots.txt
[2025-09-15 12:45:33] WARNING django.request - Not Found: /sitemap.xml
[2025-09-15 12:45:33] WARNING django.request - Not Found: /config.json
[2025-09-15 13:01:26] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:01:32] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:01:44] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:01:46] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:01:48] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:01:51] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:01:52] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:02:04] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:02:06] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:04:30] WARNING django.request - Not Found: /robots.txt
[2025-09-15 13:06:45] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:06:47] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:06:50] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:06:53] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:06:54] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:06:55] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:06:56] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:07:51] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:07:53] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:07:55] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:07:58] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:10:32] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:10:34] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:10:36] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:11:54] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:11:57] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:11:59] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:12:01] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:12:03] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:12:06] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:12:07] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:12:08] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:12:09] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:12:10] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:12:11] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:12:16] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:12:17] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:12:18] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:12:18] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:12:18] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:12:19] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:12:19] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:20:46]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 13:21:08] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:21:15] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:31:09] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:31:10] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:31:49] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:32:04] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:32:06] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:32:22] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:32:26] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:32:29] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:53:48] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:53:50] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:53:52] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:53:55] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:53:58] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:53:59] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:55:05] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:55:07] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:56:37] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:56:51] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:57:52] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 13:59:39] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:00:04] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:01:25] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:01:36] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:01:58] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:02:00] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:02:23] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:02:29] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:02:42] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:02:44] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:02:46] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:02:54] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:02:56] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:02:57] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:02:59] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:03:02] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:03:10] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:03:12] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:03:14] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:03:17] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:03:19] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:03:41] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:03:47] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:03:49] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:03:50] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:04:12] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:04:15] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:04:35] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:04:39] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:04:41] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:04:41] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:04:50] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:04:53] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:04:55] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:04:58] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:05:34] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:05:36] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:05:57] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:05:59] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:06:33] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:06:42] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:06:45] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:06:47] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:06:48] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:06:49] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:06:51] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:06:52] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:07:03] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:07:05] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:15:51] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:15:53] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:23:12]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\chemical\views.py changed, reloading.
[2025-09-15 14:23:13]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 14:24:29] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:25:11]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\nonferrous\views.py changed, reloading.
[2025-09-15 14:25:12]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 14:25:20] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:25:57]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\submaterial\views.py changed, reloading.
[2025-09-15 14:25:58]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 14:38:41]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\urls.py changed, reloading.
[2025-09-15 14:38:42]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 14:41:05]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 14:44:37]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\urls.py changed, reloading.
[2025-09-15 14:44:38]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 14:44:53]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 14:44:59]   ERROR django.request - Internal Server Error: /purchase/injection/receipts/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\injection.py", line 146, in receipt_list
    .filter(status__in=["입고대기", "입고완료"])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1481, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1499, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1506, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1523, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1330, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'status' into field. Choices are: cancel_at, cancel_by, cancel_by_id, cancel_reason, created_at, created_by, created_by_id, dlt_yn, due_date, flow_status, id, incoming_inspections, io_receipt, items, order_date, order_lot, order_status, partner_shipments, receipts, shipping_registered_at, updated_at, updated_by, updated_by_id, use_yn, vendor, vendor_id
[2025-09-15 14:44:59] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:45:00] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:45:00] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:45:01] WARNING django.request - Not Found: /accounts/login/
[2025-09-15 14:45:01] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:45:06] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:45:06] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:45:21]   ERROR django.request - Internal Server Error: /purchase/injection/receipts/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\injection.py", line 146, in receipt_list
    .filter(status__in=["입고대기", "입고완료"])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1481, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1499, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1506, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1523, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1330, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'status' into field. Choices are: cancel_at, cancel_by, cancel_by_id, cancel_reason, created_at, created_by, created_by_id, dlt_yn, due_date, flow_status, id, incoming_inspections, io_receipt, items, order_date, order_lot, order_status, partner_shipments, receipts, shipping_registered_at, updated_at, updated_by, updated_by_id, use_yn, vendor, vendor_id
[2025-09-15 14:45:21] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:45:22] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:45:22] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:45:26] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:45:31] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:45:34] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:45:35]   ERROR django.request - Internal Server Error: /purchase/injection/receipts/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\injection.py", line 146, in receipt_list
    .filter(status__in=["입고대기", "입고완료"])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1481, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1499, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1506, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1523, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1330, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'status' into field. Choices are: cancel_at, cancel_by, cancel_by_id, cancel_reason, created_at, created_by, created_by_id, dlt_yn, due_date, flow_status, id, incoming_inspections, io_receipt, items, order_date, order_lot, order_status, partner_shipments, receipts, shipping_registered_at, updated_at, updated_by, updated_by_id, use_yn, vendor, vendor_id
[2025-09-15 14:45:35] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:45:36] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:45:36] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:45:38] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:45:39] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:45:42] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:45:44] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:45:53] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:45:55] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:46:01] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:46:03] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:46:05] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:46:34] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:46:41] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:47:35] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:47:38] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:49:03]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\vendor\views.py changed, reloading.
[2025-09-15 14:49:04]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 14:49:31] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:49:32] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:50:27] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:50:30] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:50:48] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:50:49] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:57:54]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 14:57:55]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 14:58:00] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 14:58:03]   ERROR django.request - Internal Server Error: /purchase/orders/form
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\unified.py", line 534, in order_form
    vendors = _vendors_for_cat(cat)
              ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\unified.py", line 114, in _vendors_for_cat
    base = Vendor.objects.filter(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1481, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1499, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1506, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1500, in build_filter
    return self._add_q(
           ^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1523, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1330, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'trade_type' into field. Choices are: address, biz_item, biz_number, biz_type, can_login, ceo_name, chemical, contact_phone, customerorder, customuser, email, equipment, fax, id, injection, injectionorder, major_items, manager_name, name, nonferrous_set, outsourcing_type, phone, products_as_customer, products_as_injection, status, submaterial_set, transaction_type, unified_orders, unified_receipts, vendor_type, work_orders
[2025-09-15 14:58:03] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:00:04]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 15:00:05]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 15:00:49]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 15:00:50]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 15:00:52] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:00:52] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:00:55] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:00:56] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:01:03]   ERROR django.request - Internal Server Error: /purchase/orders/get-items/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\contrib\contenttypes\models.py", line 20, in get_by_natural_key
    ct = self._cache[self.db][(app_label, model)]
         ~~~~~~~~~~~^^^^^^^^^
KeyError: 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\unified.py", line 666, in get_items
    ct = ContentType.objects.get_by_natural_key(m["app"], m["model"])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\contrib\contenttypes\models.py", line 22, in get_by_natural_key
    ct = self.get(app_label=app_label, model=model)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    raise self.model.DoesNotExist(
django.contrib.contenttypes.models.ContentType.DoesNotExist: ContentType matching query does not exist.
[2025-09-15 15:01:07]   ERROR django.request - Internal Server Error: /purchase/orders/get-items/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\contrib\contenttypes\models.py", line 20, in get_by_natural_key
    ct = self._cache[self.db][(app_label, model)]
         ~~~~~~~~~~~^^^^^^^^^
KeyError: 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\unified.py", line 666, in get_items
    ct = ContentType.objects.get_by_natural_key(m["app"], m["model"])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\contrib\contenttypes\models.py", line 22, in get_by_natural_key
    ct = self.get(app_label=app_label, model=model)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    raise self.model.DoesNotExist(
django.contrib.contenttypes.models.ContentType.DoesNotExist: ContentType matching query does not exist.
[2025-09-15 15:01:20] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:01:20] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:01:24] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:01:25] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:01:25] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:01:27] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:01:31] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:01:31] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:01:38] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:01:39] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:01:41]   ERROR django.request - Internal Server Error: /purchase/orders/get-items/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\contrib\contenttypes\models.py", line 20, in get_by_natural_key
    ct = self._cache[self.db][(app_label, model)]
         ~~~~~~~~~~~^^^^^^^^^
KeyError: 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\unified.py", line 666, in get_items
    ct = ContentType.objects.get_by_natural_key(m["app"], m["model"])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\contrib\contenttypes\models.py", line 22, in get_by_natural_key
    ct = self.get(app_label=app_label, model=model)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    raise self.model.DoesNotExist(
django.contrib.contenttypes.models.ContentType.DoesNotExist: ContentType matching query does not exist.
[2025-09-15 15:05:07]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 15:05:08]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 15:05:36]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 15:05:37]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 15:06:06]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 15:06:06]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 15:06:35]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 15:06:36]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 15:07:02]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 15:07:02]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 15:08:07]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 15:08:07]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 15:08:34] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:08:36] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:08:59]   ERROR django.request - Internal Server Error: /purchase/orders/save
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ERRRAIN 11\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\unified.py", line 585, in order_save
    order = UnifiedOrder.objects.create(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 661, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\base.py", line 545, in __init__
    _setattr(self, field.name, rel_obj)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 288, in __set__
    raise ValueError(
ValueError: Cannot assign "<SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x000002BC209D3990>>": "UnifiedOrder.created_by" must be a "CustomUser" instance.
[2025-09-15 15:08:59] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:10:01] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:10:01] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:10:03] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:10:09] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:10:13] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:10:15] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:10:29]   ERROR django.request - Internal Server Error: /purchase/orders/save
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ERRRAIN 11\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\unified.py", line 585, in order_save
    order = UnifiedOrder.objects.create(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 661, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\base.py", line 569, in __init__
    raise TypeError(
TypeError: UnifiedOrder() got unexpected keyword arguments: 'remark'
[2025-09-15 15:10:29] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:10:36] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:10:36] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:10:36] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:10:36] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:20:21] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:20:46] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:20:55] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:20:59] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:21:12]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 15:21:13]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 15:21:16] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:21:16]   ERROR django.request - Internal Server Error: /purchase/injection/receipts/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\injection.py", line 146, in receipt_list
    .filter(status__in=["입고대기", "입고완료"])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1481, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1499, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1506, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1523, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1330, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'status' into field. Choices are: cancel_at, cancel_by, cancel_by_id, cancel_reason, created_at, created_by, created_by_id, dlt_yn, due_date, flow_status, id, incoming_inspections, io_receipt, items, order_date, order_lot, order_status, partner_shipments, receipts, shipping_registered_at, updated_at, updated_by, updated_by_id, use_yn, vendor, vendor_id
[2025-09-15 15:21:17] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:21:18] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:21:18] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:21:19] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:21:21] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:21:35] WARNING django.request - Bad Request: /purchase/orders/save
[2025-09-15 15:21:35] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:22:31] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:22:31] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:25:59]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 15:26:00]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 15:26:37]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 15:26:38]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 15:27:04]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 15:27:05]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 15:27:07] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:27:19]   ERROR django.request - Internal Server Error: /purchase/orders/save
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ERRRAIN 11\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\unified.py", line 621, in order_save
    rows = zip_longest(
           ^^^^^^^^^^^
NameError: name 'zip_longest' is not defined
[2025-09-15 15:27:19] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:28:43] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:28:43] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:28:46]   ERROR django.request - Internal Server Error: /purchase/orders/save
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ERRRAIN 11\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\unified.py", line 621, in order_save
    rows = zip_longest(
           ^^^^^^^^^^^
NameError: name 'zip_longest' is not defined
[2025-09-15 15:28:46]   ERROR django.request - Internal Server Error: /purchase/orders/save
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ERRRAIN 11\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\unified.py", line 621, in order_save
    rows = zip_longest(
           ^^^^^^^^^^^
NameError: name 'zip_longest' is not defined
[2025-09-15 15:28:46] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:29:50]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 15:29:51]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 15:29:52] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:29:52] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:29:54] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:30:01] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:30:59] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:31:00] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:31:03] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:31:05] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:36:43]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 15:36:43]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 15:37:10]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 15:37:11]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 15:37:46]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 15:37:47]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 15:41:01] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:41:11] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:41:26] WARNING django.request - Bad Request: /purchase/orders/save
[2025-09-15 15:41:26] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:41:45] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:41:45] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:42:06] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:47:16]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 15:47:17]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 15:55:17]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 15:55:18]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 15:55:56]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 15:55:57]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 15:56:43]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 15:56:43]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 15:57:01]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 15:57:01]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 15:57:03]   ERROR django.request - Internal Server Error: /purchase/orders/form
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\unified.py", line 560, in order_form
    return render(
           ^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 489, in parse
    raise self.error(token, e)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 710, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':'Y-m-d'' from 'today|default:date:'Y-m-d''
[2025-09-15 15:57:03] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:57:23]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 15:57:24]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 15:57:30]   ERROR django.request - Internal Server Error: /purchase/orders/form
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\unified.py", line 561, in order_form
    return render(
           ^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 489, in parse
    raise self.error(token, e)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 487, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 609, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\template\base.py", line 710, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ':'Y-m-d'' from 'today|default:date:'Y-m-d''
[2025-09-15 15:57:30] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:59:05] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:59:09] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:59:12] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:59:26] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:59:30] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:59:30] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:59:34] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:59:39] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:59:39] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:59:43] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 15:59:58] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:00:00] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:00:04] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:00:07] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:06:05]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 16:06:06]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 16:06:39]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 16:06:40]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 16:06:55]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 16:06:56]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 16:07:08]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 16:07:08]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 16:08:28] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:08:28] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:08:30] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:16:45] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:16:48] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:16:55] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:16:56] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:17:00] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:17:04] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:17:04] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:17:05] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:17:05] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:17:07] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:17:09] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:17:10] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:17:21] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:17:26] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:17:27] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:17:29] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:17:34] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:17:36] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:17:38] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:17:40] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:17:43] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:17:46] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:17:52] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:17:58] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:17:59] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:18:00] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:18:03] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:18:04] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:18:04] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:18:04] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:18:06] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:18:07] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:18:12] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:18:14] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:18:18] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:18:20] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:18:21] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:18:27] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:18:28] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:18:30] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:18:32] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:18:34] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:18:43] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:18:45] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:18:46] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:18:50] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:18:53] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:19:16]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 16:19:17]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 16:19:20] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:19:22] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:19:24] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:22:21] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:22:32] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:23:55] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:23:58]   ERROR django.request - Internal Server Error: /purchase/orders/get-items/
[2025-09-15 16:24:04] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:24:05] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:24:10] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:24:10] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:24:12]   ERROR django.request - Internal Server Error: /purchase/orders/get-items/
[2025-09-15 16:27:52] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:28:16] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:28:27] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:28:49] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:28:57]   ERROR django.request - Internal Server Error: /purchase/injection/receipts/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\injection.py", line 146, in receipt_list
    .filter(status__in=["입고대기", "입고완료"])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1481, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1499, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1506, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1523, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1330, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'status' into field. Choices are: cancel_at, cancel_by, cancel_by_id, cancel_reason, created_at, created_by, created_by_id, dlt_yn, due_date, flow_status, id, incoming_inspections, io_receipt, items, order_date, order_lot, order_status, partner_shipments, receipts, shipping_registered_at, updated_at, updated_by, updated_by_id, use_yn, vendor, vendor_id
[2025-09-15 16:28:57] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:28:58] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:28:58] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:28:59] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:29:01] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:29:55] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:29:57] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:29:59] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:29:59] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:41:44]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 16:41:45]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 16:42:46] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:42:48] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:42:54] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:42:55] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:43:31]   ERROR django.request - Internal Server Error: /purchase/orders/get-items/
[2025-09-15 16:43:36] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:43:39] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:43:46] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:43:46] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:43:48] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:43:48] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:43:50] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:43:56] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:44:00]   ERROR django.request - Internal Server Error: /purchase/orders/get-items/
[2025-09-15 16:44:07] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:44:10] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:44:18] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:44:22] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:44:22] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:44:22] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:44:22] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:44:25] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:44:27] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:44:29] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:44:29] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:44:30] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:44:30] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:45:46] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:45:48] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:46:11] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:50:08]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 16:50:09]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 16:51:07]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 16:51:08]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 16:52:00]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 16:52:01]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 16:54:48]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 16:54:49]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 16:54:50] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:55:40]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 16:55:45] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:55:47] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:58:28]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 16:58:29]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 16:59:22]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 16:59:23]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 16:59:35] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 16:59:48] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 17:01:13] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 17:01:15]   ERROR django.request - Internal Server Error: /purchase/orders/get-items/
[2025-09-15 17:01:16] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 17:01:42] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 17:02:24] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 17:06:26] WARNING django.request - Not Found: /favicon.ico
[2025-09-15 17:10:25]   ERROR django.request - Internal Server Error: /quality/incoming/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\quality\views.py", line 20, in incoming_list
    qs = InjectionOrder.objects.filter(status='입고대기', dlt_yn='N').select_related('vendor')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1481, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1499, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1506, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1523, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1330, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'status' into field. Choices are: cancel_at, cancel_by, cancel_by_id, cancel_reason, created_at, created_by, created_by_id, dlt_yn, due_date, flow_status, id, incoming_inspections, io_receipt, items, order_date, order_lot, order_status, partner_shipments, receipts, shipping_registered_at, updated_at, updated_by, updated_by_id, use_yn, vendor, vendor_id
[2025-09-15 17:10:46]   ERROR django.request - Internal Server Error: /purchase/injection/receipts/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\injection.py", line 146, in receipt_list
    .filter(status__in=["입고대기", "입고완료"])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1481, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1499, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1506, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1523, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1330, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'status' into field. Choices are: cancel_at, cancel_by, cancel_by_id, cancel_reason, created_at, created_by, created_by_id, dlt_yn, due_date, flow_status, id, incoming_inspections, io_receipt, items, order_date, order_lot, order_status, partner_shipments, receipts, shipping_registered_at, updated_at, updated_by, updated_by_id, use_yn, vendor, vendor_id
[2025-09-15 17:12:59] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 17:13:15] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 17:13:15] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 17:15:05] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 17:15:47] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 17:55:41]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\urls.py changed, reloading.
[2025-09-15 17:55:42]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 17:55:45] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 17:55:47] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 17:56:17] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:00:52] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:00:53] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:00:57] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:01:00] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:02:49] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:02:52] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:02:53] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:02:56] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:03:39] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:03:41] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:03:42] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:03:54] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:04:00] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:04:02] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:04:03]   ERROR django.request - Internal Server Error: /purchase/injection/receipts/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\injection.py", line 146, in receipt_list
    .filter(status__in=["입고대기", "입고완료"])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1481, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1499, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1506, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1523, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1330, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'status' into field. Choices are: cancel_at, cancel_by, cancel_by_id, cancel_reason, created_at, created_by, created_by_id, dlt_yn, due_date, flow_status, id, incoming_inspections, io_receipt, items, order_date, order_lot, order_status, partner_shipments, receipts, shipping_registered_at, updated_at, updated_by, updated_by_id, use_yn, vendor, vendor_id
[2025-09-15 18:04:03] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:04:04] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:04:04] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:04:05] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:04:07] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:04:23] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:04:26] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:04:26] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:05:24] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:05:25] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:05:42] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:05:42] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:05:44] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:07:02] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:07:04] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:07:20] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:07:22] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:07:27] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:07:29] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:07:33] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:07:38] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:07:42] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:07:46] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:15:14] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:18:12] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:27:28] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:35:22]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 18:35:23]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 18:35:26] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:35:28] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:35:30] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:35:51] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:38:23] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:38:35] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:40:40] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:40:41] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:40:50]   ERROR django.request - Internal Server Error: /purchase/injection/receipts/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\injection.py", line 146, in receipt_list
    .filter(status__in=["입고대기", "입고완료"])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1481, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1499, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1506, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1523, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1330, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'status' into field. Choices are: cancel_at, cancel_by, cancel_by_id, cancel_reason, created_at, created_by, created_by_id, dlt_yn, due_date, flow_status, id, incoming_inspections, io_receipt, items, order_date, order_lot, order_status, partner_shipments, receipts, shipping_registered_at, updated_at, updated_by, updated_by_id, use_yn, vendor, vendor_id
[2025-09-15 18:40:50]   ERROR django.request - Internal Server Error: /purchase/injection/receipts/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\injection.py", line 146, in receipt_list
    .filter(status__in=["입고대기", "입고완료"])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1481, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1499, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1506, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1523, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1330, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'status' into field. Choices are: cancel_at, cancel_by, cancel_by_id, cancel_reason, created_at, created_by, created_by_id, dlt_yn, due_date, flow_status, id, incoming_inspections, io_receipt, items, order_date, order_lot, order_status, partner_shipments, receipts, shipping_registered_at, updated_at, updated_by, updated_by_id, use_yn, vendor, vendor_id
[2025-09-15 18:40:50] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:40:54] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:40:54] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:41:47] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:41:48] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:41:48] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:42:01]   ERROR django.request - Internal Server Error: /quality/incoming/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\quality\views.py", line 20, in incoming_list
    qs = InjectionOrder.objects.filter(status='입고대기', dlt_yn='N').select_related('vendor')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1481, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1499, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1506, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1523, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1330, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'status' into field. Choices are: cancel_at, cancel_by, cancel_by_id, cancel_reason, created_at, created_by, created_by_id, dlt_yn, due_date, flow_status, id, incoming_inspections, io_receipt, items, order_date, order_lot, order_status, partner_shipments, receipts, shipping_registered_at, updated_at, updated_by, updated_by_id, use_yn, vendor, vendor_id
[2025-09-15 18:42:01] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:42:06] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:42:06] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:42:32] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:42:36]   ERROR django.request - Internal Server Error: /purchase/injection/receipts/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\injection.py", line 146, in receipt_list
    .filter(status__in=["입고대기", "입고완료"])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1481, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1499, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1506, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1523, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1330, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'status' into field. Choices are: cancel_at, cancel_by, cancel_by_id, cancel_reason, created_at, created_by, created_by_id, dlt_yn, due_date, flow_status, id, incoming_inspections, io_receipt, items, order_date, order_lot, order_status, partner_shipments, receipts, shipping_registered_at, updated_at, updated_by, updated_by_id, use_yn, vendor, vendor_id
[2025-09-15 18:42:36] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:42:37] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:42:37] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:42:55] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:43:41] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:43:55] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:44:54] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:45:01] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:45:18] WARNING django.request - Not Found: /robots.txt
[2025-09-15 18:45:28] WARNING django.request - Not Found: /favicon.ico
[2025-09-15 18:46:01] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:46:01] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:46:21] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:47:10] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:48:12] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:49:18]   ERROR django.request - Internal Server Error: /quality/incoming/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\quality\views.py", line 20, in incoming_list
    qs = InjectionOrder.objects.filter(status='입고대기', dlt_yn='N').select_related('vendor')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1481, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1499, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1506, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1523, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1330, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'status' into field. Choices are: cancel_at, cancel_by, cancel_by_id, cancel_reason, created_at, created_by, created_by_id, dlt_yn, due_date, flow_status, id, incoming_inspections, io_receipt, items, order_date, order_lot, order_status, partner_shipments, receipts, shipping_registered_at, updated_at, updated_by, updated_by_id, use_yn, vendor, vendor_id
[2025-09-15 18:49:18] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:49:20] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:49:20] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:52:07]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\urls.py changed, reloading.
[2025-09-15 18:52:07]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 18:53:05]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\urls.py changed, reloading.
[2025-09-15 18:53:05]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 18:53:08] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:53:11] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:53:16] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:53:16] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:53:18] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:53:21] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:53:21] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 18:53:24] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 19:01:02]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\urls.py changed, reloading.
[2025-09-15 19:01:03]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 19:08:02]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 19:08:03]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 19:10:49]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\urls.py changed, reloading.
[2025-09-15 19:10:50]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 19:10:54]   ERROR django.request - Internal Server Error: /purchase/injection/receipts/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\injection.py", line 146, in receipt_list
    .filter(status__in=["입고대기", "입고완료"])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1481, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1499, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1506, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1523, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1330, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'status' into field. Choices are: cancel_at, cancel_by, cancel_by_id, cancel_reason, created_at, created_by, created_by_id, dlt_yn, due_date, flow_status, id, incoming_inspections, io_receipt, items, order_date, order_lot, order_status, partner_shipments, receipts, shipping_registered_at, updated_at, updated_by, updated_by_id, use_yn, vendor, vendor_id
[2025-09-15 19:10:54] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 19:10:54] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 19:10:54] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 19:10:56] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 19:15:25] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 19:15:29] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 19:15:34] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 19:15:35] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 19:15:37] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 19:15:39] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 19:15:39] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 19:15:45] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 19:16:05]   ERROR django.request - Internal Server Error: /purchase/injection/receipts/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\injection.py", line 146, in receipt_list
    .filter(status__in=["입고대기", "입고완료"])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1481, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1499, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1506, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1523, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1330, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1802, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'status' into field. Choices are: cancel_at, cancel_by, cancel_by_id, cancel_reason, created_at, created_by, created_by_id, dlt_yn, due_date, flow_status, id, incoming_inspections, io_receipt, items, order_date, order_lot, order_status, partner_shipments, receipts, shipping_registered_at, updated_at, updated_by, updated_by_id, use_yn, vendor, vendor_id
[2025-09-15 19:16:05] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 19:16:05] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 19:16:05] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 19:16:08] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 19:16:09] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 19:16:13] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 19:16:20] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 19:16:47] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 19:23:24] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 19:41:16] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 19:41:20] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 19:41:22] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 19:53:14]    INFO django.utils.autoreload - E:\pythonspace\skerp_project\purchase\views\unified.py changed, reloading.
[2025-09-15 19:53:15]    INFO django.utils.autoreload - Watching for file changes with StatReloader
[2025-09-15 20:00:29] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 20:00:35] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 20:00:40] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 20:00:42] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 20:00:48] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 20:00:49]   ERROR django.request - Internal Server Error: /production/orders/reorder/
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2128, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'undefined'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ERRRAIN 11\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\production\orders\views.py", line 196, in order_reorder
    wos = list(WorkOrder.all_objects.filter(pk__in=ids))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1481, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1499, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\query.py", line 1506, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1643, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1675, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1585, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\sql\query.py", line 1412, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\lookups.py", line 38, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\lookups.py", line 536, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\lookups.py", line 321, in get_prep_lookup
    rhs_value = self.lhs.output_field.get_prep_value(rhs_value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2130, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'undefined'.
[2025-09-15 20:00:53] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 20:01:12] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 20:01:37] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 20:01:40] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
[2025-09-15 20:01:43]   ERROR django.request - Internal Server Error: /purchase/orders/7/edit
Traceback (most recent call last):
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\views\decorators\http.py", line 64, in inner
    return func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\purchase\views\unified.py", line 670, in order_edit
    "form_action": reverse("purchase:uni_order_update", args=[order.id]),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\urls\base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\pythonspace\skerp_project\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'uni_order_update' not found. 'uni_order_update' is not a valid view function or pattern name.
[2025-09-15 20:01:43] WARNING django.request - Not Found: /.well-known/appspecific/com.chrome.devtools.json
